#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "call/call.h"
#include "push/push.h"
#include "test/test.h"
#include "je/je.h"
#include "cmp/cmp.h"
#include "ret/ret.h"
#include "pop/pop.h"
#include "sub/sub.h"
#include "jmp/jmp.h"
#include "jbe/jbe.h"
#include "sete/sete.h"
#include "stos/stos.h"
#include "lea/lea.h"
#include "sbb/sbb.h"
#include "movs/movs.h"
#include "int/int.h"
#include "scars/scas.h"
#include "js/js.h"
#include "ja/ja.h"
#include "jns/jns.h"
#include "jge/jge.h"
#include "movsx/movsx.h"
#include "jg/jg.h"
#include "jl/jl.h"
#include "leave/leave.h"
#include "setne/setne.h"
#include "add/add.h"
#include "jle/jle.h"
#include "adc/adc.h"
#include "jne/jne.h"
#include "movzb/movzx.h"
#include "data-mov/xchg.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"
